server:
  port: 8001

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mariadb://localhost:3306/remylia_auth
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 10000
      minimum-idle: 5
      connection-timeout: 15000
      pool-name: hikari-pool
      max-lifetime: 60000
  jpa:
    show-sql: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8100/eureka

error-codes:
  SUCCESS: 200
  CREATED: 201
  DATA_INVALID: 400
  EMAIL_INVALID: 400
  PASSWORD_WEAK: 400
  EMAIL_EXISTED: 400
  INTERNAL_ERROR: 500

redisson:
  clusterServersConfig:
    nodeAddresses:
      - redis://192.168.1.10:8021
      - redis://192.168.1.10:8022
      - redis://192.168.1.10:8023
      - redis://192.168.1.11:8021
      - redis://192.168.1.11:8022
      - redis://192.168.1.11:8023
      - redis://192.168.1.12:8021
      - redis://192.168.1.12:8022
      - redis://192.168.1.12:8023
    scanInterval: 2000
    password: "Redis@2024"
    retryAttempts: 0
    retryInterval: 2000
    connectTimeout: 100
    timeout: 3000
    masterConnectionPoolSize: 64
    slaveConnectionPoolSize: 64

#clusterServersConfig:
#  nodeAddresses:
#    - redis://192.168.1.10:8021
#    - redis://192.168.1.10:8022
#    - redis://192.168.1.10:8023
#    - redis://192.168.1.11:8021
#    - redis://192.168.1.11:8022
#    - redis://192.168.1.11:8023
#    - redis://192.168.1.12:8021
#    - redis://192.168.1.12:8022
#    - redis://192.168.1.12:8023
#  scanInterval: 2000
#  password: "Redis@2024"
#  retryAttempts: 5
#  retryInterval: 2000
#  connectTimeout: 10000
#  timeout: 3000
#  masterConnectionPoolSize: 64
#  slaveConnectionPoolSize: 64