server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/point
    username: hungnt
    password: hungnt
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 10000
      minimum-idle: 5
      connection-timeout: 15000
      pool-name: hikari-pool
      max-lifetime: 60000
  jpa:
    show-sql: true

  kafka:
    # topicTest: topicTest
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: topicTest1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer